import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import PP from '../../public/images/profile/developer-pic-1.png'
import AnimatedText from '@/components/AnimatedText'
import Lottie, {LottieRefCurrentProps} from "lottie-react"
import animationData from "/bot.json"
import {useRef} from 'react'


export default function Home() {
  const botRef = useRef<LottieRefCurrentProps>(null)
  return (
    <>

      <Head>
        <title>Harsha G</title>
        <meta name="description" content="Generated by create next app" /> 
      </Head>

      <main className='flex items-center text-dark w-full min-h-screen' >
       <Layout className='pt-0'>

          <div className='flex items-center justify-between w-full'>
          
            <div className='w-1/2'>
              
              <Lottie onComplete={() => {
              botRef.current?.goToASndPlay(45,true)
              
              }} lottieref={botRef}animationData={animationData} className/> 
                         
            </div>

            <div className='w-1/2 flex flex-col items-center self-center'> 
              <AnimatedText text="Turning Vision Into Reality With Code And Design." className='!text-6xl !text-left'/>
              <p>
              As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
              Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>
            </div>
          </div>
       </Layout>
      </main>

    </>
  )
}
